### ISSUE TITLE
Unity not launching Rider on Mac

### ISSUE THREAD

**Issue by Beatn1ck** [JetBrains/Unity3dRider#10]
Hello,
So I have followed the steps listed on the Readme, on PC and Mac.  On PC it works pretty great, but on the mac I'm getting an error when I try to launch Rider EAP. This is what I'm seeing. 
ArgumentException: An empty file name is not valid.
System.IO.FileSystemInfo.CheckPath (System.String path) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileSystemInfo.cs:255)
System.IO.FileInfo..ctor (System.String fileName) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileInfo.cs:58)
(wrapper remoting-invoke-with-check) System.IO.FileInfo:.ctor (string)
Assets.Plugins.Editor.Rider.Rider..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Assets.Plugins.Editor.Rider.Rider
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:123)
UnityEditor.DockArea:OnGUI()
I have the latest version of Rider EAP.  I'm using Unity 5.4.1f1

**Comment by van800** [comment]
Please add everything from the Unity debug log. Thanks!

**Comment by van800** [comment]
double click on file doesnt work either?

**Comment by Beatn1ck** [comment]
That is everything from the Unity debug log when I double click on a file from Unity.  I restarted Unity and it seems to be working now, however.
