### ISSUE TITLE
Namespace ending with Rider conflicts with Rider class name.

### ISSUE THREAD

**Issue by Silphid** [JetBrains/Unity3dRider#12]
I had to remove the Rider suffix of namespace in all three files for the code to compile.  Wonder why you are not encountering that issue on your side.  Maybe because I am compiling with "C# 6.0 Support"?

**Comment by van800** [comment]
Please check that all 3 files are in
namespace Assets.Plugins.Editor.Rider

**Comment by Silphid** [comment]
I'm not sure you understood my explanation correctly.  The namespaces should NOT use "Rider" in their name, because there is already a class named "Rider" and they conflict together.

See: https://blogs.msdn.microsoft.com/ericlippert/2010/03/09/do-not-name-a-class-the-same-as-its-namespace-part-one/

**Comment by van800** [comment]
I have updated the name Rider to RiderPlugin and some small refactoring. And if is doesn't help, then feel free to submit a PR.
