### ISSUE TITLE
Elaboration on how to debug

### ISSUE THREAD

**Issue by itaibsn** [JetBrains/Unity3dRider#13]
The description says-

> To debug Unity in Rider call Run-> Attach to local processes

Well, it looks like 'Attach to local processes' is not active by default (grayed out). Maybe need some configuration?

**Comment by van800** [comment]
What is your OS? Thanks!

**Comment by itaibsn** [comment]
Windows, and thank you...

**Comment by van800** [comment]
I have made a request https://youtrack.jetbrains.com/issue/RIDER-2880 for the problem. Please attach Rider logs to it. It will really help. Thank you!
