### ISSUE TITLE
Ambiguity about where placing the script

### ISSUE THREAD

**Issue by itaibsn** [JetBrains/Unity3dRider#14]
Description says - 

> Put the folder Assets/Plugins/Editor/Rider from this repository into Assets/Plugins/Editor/Rider in your project.

but RiderPlugin.cs has a comment says 

`
// Put the file to Assets/Plugins/Rider/Editor/ for Unity 5.2.2+
// the file to Assets/Plugins/Editor/Rider for Unity prior 5.2.2
`

**Comment by z3ntu** [comment]
I have the files in `Assets/Plugins/Editor/Rider/` for the newest beta of Unity and it works as expected.

**Comment by van800** [comment]
Thanks for pointing out.
