### ISSUE TITLE
Rider does not recognize the UnityEditor.iOS.Xcode namespace

### ISSUE THREAD

**Issue by cmcpasserby** [JetBrains/Unity3dRider#15]
what the title says, it can see the `UnityEditor.iOS` namespace but not the `UnityEditor.iOS.Xcode`

**Comment by van800** [comment]
Hi! 
How is it related to the plugin?
I would suggest, first check references, if there are some unresolved?

**Comment by Dukobpa3** [comment]
It is related to the plugin. I think.
There was the same issue in the MonoDevelop and it was fixed by the Unity team in the MonoDevelop-Unity integration part

**Comment by van800** [comment]
https://issuetracker.unity3d.com/issues/unity-does-not-include-unityeditor-dot-ios-dot-xcode-in-project-file

Which version of Unity do you use?

**Comment by cmcpasserby** [comment]
5.4.1

**Comment by van800** [comment]
Please try to update to at least Unity 5.4.2.

**Comment by Dukobpa3** [comment]
VS 2013|2015 don't have this issue.

**Comment by van800** [comment]
Summarizing my findings:
Pre-condition: iOS Support needs to be installed in Unity. File->Build And Run ->iOS. Download link is there.
2. For Rider/MonoDevelop/(Any editor except VS) Unity doesn't create a correct csproj file - it references to assembly is missing
    <Reference Include="UnityEditor.iOS.Extensions.Xcode">
      <HintPath>Library\UnityAssemblies\UnityEditor.iOS.Extensions.Xcode.dll</HintPath>
    </Reference>
3. Specially for VS Unity creates a csproj file with different name and contents.

Is it a problem for someone on OSX?

**Comment by van800** [comment]
In regular csproj references are like:
C:/Program Files/Unity/Editor/Data/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll
But in VS csproj:
Assemblies are pre-copied to Library folder near csproj file:
<HintPath>Library\UnityAssemblies\UnityEngine.dll</HintPath>

**Comment by van800** [comment]
short workaround for Windows might be adding 

> <Reference Include="UnityEditor.iOS.Extensions.Xcode">
>       <HintPath>C:/Program Files/Unity/Editor/Data/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll</HintPath>
>     </Reference>

in RiderAssetPostprocessor.UpgradeProjectFile

**Comment by Dukobpa3** [comment]
> Is it a problem for someone on OSX?

Yes, I'm workin' on mac

**Comment by van800** [comment]
For mac paths must be 
"/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll" and
"/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Common.dll"

**Comment by cmcpasserby** [comment]
yeah i was testing on the Mac side of things as well, it seems that for visual studio it does generate a slightly differing projects.

`    <Reference Include="UnityEditor.iOS.Extensions.Xcode">
      <HintPath>Library\UnityAssemblies\UnityEditor.iOS.Extensions.Xcode.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor.iOS.Extensions.Common">
      <HintPath>Library\UnityAssemblies\UnityEditor.iOS.Extensions.Common.dll</HintPath>
    </Reference>
`

these lines are present in solutions generated for Visual Studio in unity, but are not present for ones generated for other IDES.

**Comment by van800** [comment]
the code in the Unity3dRider, which is workarounding the issue was removed for Unity 2017.1 and newer, because Unity has fixed the problem by itself.
https://github.com/JetBrains/resharper-unity/commit/3a523f158df7cedea57feb8fed2d028470d3b031
