### ISSUE TITLE
Please make sync moving files in the rider with the unity metafiles

### ISSUE THREAD

**Issue by Dukobpa3** [JetBrains/Unity3dRider#17]
This feature is present in the MonoDevelop as separated plugin and in the VS by default.

Scripts linking drops from prefabs after moving files inside rider.

**Comment by van800** [comment]
I have moved the request to more appropriate place
https://github.com/JetBrains/resharper-unity/issues/61

**Comment by Dukobpa3** [comment]
How resharper depends to Rider plugin?

**Comment by van800** [comment]
Rider has full-featured ReSharper on backend. So resharper-unity plugin is used for both ReSharper and Rider.

**Comment by Dukobpa3** [comment]
Ahhh, ok thanks!
