### ISSUE TITLE
Rider does not find namespace from DLL (FirebaseAnalytics)

### ISSUE THREAD

**Issue by Toriath** [JetBrains/Unity3dRider#20]
Hi,

I've just tried to integrate the new FirebaseAnalytics for Unity [(This)](https://firebase.google.com/docs/unity/setup) into my Project and it seems to me that Rider does not find the namespace from the DLL. The build from Unity does work. Both MonoDevelop and VisualStudio are able to find the namespace.

Is this related to the Plugin or is this probably not yet working in rider at all?

Please feel free to ask me more about this issue but at the current time, I don't have more information.

**Comment by van800** [comment]
Hi,

I tried to reproduce your case, but everything worked for me.
Let me know your Rider version (for now latest eap build is 163.7608), maybe OS would be relevant.
I followed this instructions to import FirebaseAnalytics.
https://firebase.google.com/docs/unity/setup

**Comment by Toriath** [comment]
Hi,
I am using the latest EAP Build (163.7608) on Windows 10 - 64 Bit
I have also tried to open the project on my Laptop with Windows 8.1 - 64 Bit which does not work too.

Maybe the Google Play Game Services Plugin [(This)](https://github.com/playgameservices/play-games-plugin-for-unity) got something to do with it.

I'll try to reinstall Rider in the mean time.

**Comment by van800** [comment]
Please check if you have a valid reference 
<Reference Include="Firebase.Analytics">
In csproj files in your solution.
I don't think reinstalling Rider might help for the case.

**Comment by Toriath** [comment]
In Assembly-CSharp the following references are invalid.
* Firebase.Analytics
* Firebase.App

This is what the .csproj-File contains about them:

`<Reference Include="Firebase.Analytics">`      `<HintPath>C:/Users/kloss/UnityProjects/JumpyGap/Assets/Firebase/Plugins/Firebase.Analytics.dll</HintPath>`
`</Reference>`
`<Reference Include="Firebase.App">    `  `<HintPath>C:/Users/kloss/UnityProjects/JumpyGap/Assets/Firebase/Plugins/Firebase.App.dll</HintPath>`
`</Reference>`

The whole Assets/Firebase/Plugins Folder is not visible in Rider

**Comment by Toriath** [comment]
I have removed the Entries from the .csproj-File and readded the references manually via Rider. 
This way it is working now.

**Comment by van800** [comment]
Unity is recreating csproj files on every major change, like adding file to project.
What is a correct path to Firebase.Analytics.dll?

**Comment by van800** [comment]
Please compare csproj, which Unity creates for MonoDevelop and for Rider.
I am still trying to reproduce it on my side, but no success for now.

**Comment by Toriath** [comment]
These are both Files. Plain Unity and after adding rider References.

[Assembly-CSharp.csproj.UNITY.txt](https://github.com/JetBrains/Unity3dRider/files/583798/Assembly-CSharp.csproj.UNITY.txt)

[Assembly-CSharp.csproj.RIDER.txt](https://github.com/JetBrains/Unity3dRider/files/583799/Assembly-CSharp.csproj.RIDER.txt)

**Comment by van800** [comment]
Thanks! I have reproduced the issue. Let me investigate it.

**Comment by van800** [comment]
I can't get completely the same double reference to Firebase.Analytics.dll in csproj as you submitted.
But I saw them unresolved in Rider.

Please try the fast fix, which worked for me
comment out lines 32, 33, 38 in RiderAssetPostProcessor.cs
32 must be if (!RiderPlugin.IsWindows)

**Comment by Toriath** [comment]
Will try this ASAP but won't be back till tomorrow.

Ivan Shakhov <notifications@github.com> schrieb am Do., 10. Nov. 2016,
17:37:

**Comment by van800** [comment]
Ah, sorry, I was looking on the outdated sources. 

Please comment out lines 
      if (RiderPlugin.IsWindows)
        return;
in RiderAssetPostProcessor.cs

**Comment by van800** [comment]
I added a request https://youtrack.jetbrains.com/issue/RIDER-3199

**Comment by Toriath** [comment]
Commenting 
`if (RiderPlugin.IsWindows)`
`return;`
in RiderAssetPostProcessor.cs

fixed it for me too. Thanks :)

**Comment by van800** [comment]
setting to 4.5 for everybody would contradict with
https://github.com/JetBrains/Unity3dRider/issues/9

**Comment by van800** [comment]
22ba2db77873eef63569b78247b4aa321553ad85
