### ISSUE TITLE
Feature Request: Shader highlighting

### ISSUE THREAD

**Issue by Skjalgsm** [JetBrains/Unity3dRider#21]
When opening a .shader file in rider the file appears greyed out with no syntax highlighting. Would be nice if this was supported out of the box.

**Comment by van800** [comment]
Definitelly not the right place for request like this. Please submit to https://youtrack.jetbrains.com/issues/RIDER
Meanwhile, there is already some community support for it. Follow here
https://twitter.com/borodargames/status/790577596106956801
https://gist.github.com/PhannGor/fe73256b8c5c78a1b236e8c919e3d08d

**Comment by Skjalgsm** [comment]
Why is this definitively something that can't be done with this plugin if another plugin already has some basic support for it?

**Comment by van800** [comment]
It might get hard to support the "super plugin".
As far as I understood that shader support is not a plugin, it is just a file, which needs to be manually copied to Rider config folder.
