### ISSUE TITLE
Mac OS Sierra. Rider doesn't connects to debug

### ISSUE THREAD

**Issue by Dukobpa3** [JetBrains/Unity3dRider#22]
Subj.
When I'm clicking "Debug" button - nothing happens.

**Comment by YouHusam** [comment]
Select Run > Attach to local process from the menu bar

**Comment by Dukobpa3** [comment]
Yes, just found answer here.
https://youtrack.jetbrains.com/issue/RIDER-485

Is it only way to do it? Can I configure debug configuration for doing it in one click?

**Comment by van800** [comment]
Debugging of Unity instances.

    Use the Run → "Attach to local process" menu item to list available Unity instances.
    Run → "Edit Configurations" → Add new "Mono remote" configuration to set everything manually.

**Comment by van800** [comment]
Try to set the keyboard shortcut for "attach to local processes".

**Comment by van800** [comment]
Do you mean a shortcut to debug UnityEditor at once?

**Comment by Dukobpa3** [comment]
Yes. Something like "f9".
I've tried few variants host:port for mono remote debut but no one works for me.
Do you know the needed values?

**Comment by van800** [comment]
It will not work out for your case, because the values change with each Unity restart.

**Comment by van800** [comment]
You may use the code, which was removed here https://github.com/JetBrains/Unity3dRider/commit/9c4a811fe593ffdf9dfd83764bed34ddf8745d5c
specifically UpdateDebugSettings
to autogenerate the debug RunConfiguration.

**Comment by Dukobpa3** [comment]
Ok. Thanks!

**Comment by van800** [comment]
I added a request https://youtrack.jetbrains.com/issue/RIDER-3260 for Rider itself to facilitate Debug in one click. Please vote it.

**Comment by aaronjbaptiste** [comment]
@Dukobpa3 I can't get rider to work at all on Sierra. Do you not encounter this error?: [MsBuild model already detached from protocol](https://youtrack.jetbrains.com/issue/DEXP-144141)

**Comment by van800** [comment]
@aaronjbaptiste do you have some special settings in Mono and Toolset in Rider settings? Akso check mono version (used by Rider)

**Comment by aaronjbaptiste** [comment]
@van800  My mono version: Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:48 PDT 2016). Not sure what Rider requires? No special settings, default installation of mono, unity (5.4.2f2) and rider.

**Comment by van800** [comment]
@aaronjbaptiste I answered [here](https://youtrack.jetbrains.com/issue/RIDER-3356)
