### ISSUE TITLE
Feature Request: Swap Tolerance with Mathf.Epsilon

### ISSUE THREAD

**Issue by Skjalgsm** [JetBrains/Unity3dRider#23]
When rider detects floating point imprecision in my code it wants to fix it by Adding Math.Abs and checking if it is less than TOLERANCE. I'd like TOLERANCE to be swapped out with Mathf.epsilon in the UnityEngine.dll

![image](https://cloud.githubusercontent.com/assets/568589/20385127/71283e64-acb6-11e6-9f65-3fa9f9eb7b4b.png)
![image](https://cloud.githubusercontent.com/assets/568589/20385115/6692f566-acb6-11e6-8e25-1190ad921107.png)
![image](https://cloud.githubusercontent.com/assets/568589/20385166/9ffbe150-acb6-11e6-8b0c-a8af7d6b5951.png)

**Comment by citizenmatt** [comment]
This would be better as an issue against the [JetBrains/resharper-unity](https://www.github.com/JetBrains/resharper-unity) repo, as that plugin provides the C# language features for Unity.

This plugin (Unity3dRider) is purely about getting Unity to open files in Rider. We're hoping it will go away in a [future version of Unity](https://feedback.unity3d.com/suggestions/project-rider-c-number-ide-support).

**Comment by Skjalgsm** [comment]
https://github.com/JetBrains/resharper-unity/issues/68
