### ISSUE TITLE
Feature Request: Add .meta file to git automatically when creating a new script

### ISSUE THREAD

**Issue by Skjalgsm** [JetBrains/Unity3dRider#24]
When I add a new script using rider it automatically adds the file to git, but not the meta file. It would be nice if this was added as well.
![image](https://cloud.githubusercontent.com/assets/568589/20393000/7c3a0fd4-acda-11e6-91e4-63de81b73568.png)

**Comment by citizenmatt** [comment]
This would be better as an issue against the [JetBrains/resharper-unity](https://www.github.com/JetBrains/resharper-unity) repo, as that plugin provides the C# language features for Unity, and will probably extend to include Rider specific functionality, too. There are similar issues already there - JetBrains/resharper-unity#61 + JetBrains/resharper-unity#29.

This plugin (Unity3dRider) is purely about getting Unity to open files in Rider - it's a plugin to Unity, not Rider. We're hoping it will go away in a [future version of Unity](https://feedback.unity3d.com/suggestions/project-rider-c-number-ide-support).

**Comment by Skjalgsm** [comment]
Ah that makes a lot of sense. Feel free to close this
