### ISSUE TITLE
Opening rider from xml file in unity project does not work

### ISSUE THREAD

**Issue by Skjalgsm** [JetBrains/Unity3dRider#25]
When double clicking on an xml file in unity it gives an error
![image](https://cloud.githubusercontent.com/assets/568589/20393252/7150889a-acdb-11e6-95f3-b50909c75fd0.png)

**Comment by van800** [comment]
Thanks for reporting this.
We use [UnityEditor.Callbacks.OnOpenAssetAttribute()] to get notified about opening file, but for xml and txt it doesn't fire up. I am searching for different option to fix it.

**Comment by van800** [comment]
Unfortunately this will not work for Linux and Mac.

**Comment by van800** [comment]
Fix for this problem may lead to other possible problem.
This was fixed by adding path to sln to kScriptEditorArgs.
But if I will open other Unity solution which doesn't contain Unity3dRider then path to sln would be wrong.

**Comment by van800** [comment]
Finally I have found the cause of the problem in my code. New fix was done here 
https://github.com/JetBrains/resharper-unity/commit/ebc634f1550390bb2d0a29c60a111f023f7399d7
