### ISSUE TITLE
Sometimes opening file in Unity fails to bring Rider to the front

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/Unity3dRider#26]
From twitter (@Skjalgsm):

> after about half an hours use it stops opening files when I double click the console in #unity3d

and

> I mean, it opens the file in rider, but rider is not switched to immediately. I have to alt tab to it.

**Comment by Skjalgsm** [comment]
It actually selects the file in Rider, it just doesn't bring it to the front.

It stops working sometimes after just a few minutes, sometimes after half an hour.

It never works with xml or txt files, so thats the easiest way to reproduce it.

**Comment by van800** [comment]
xml and txt is 95% other case.

**Comment by Skjalgsm** [comment]
I've opened a second issue for the xml files then https://github.com/JetBrains/Unity3dRider/issues/25

**Comment by citizenmatt** [comment]
For the files that are opening, but not bringing the app to the front, can you check the output window in Unity to see if there are any log messages, please? E.g. `Exception on ActivateWindow`. Also, you could attach the Rider debugger to Unity, then try and open a file, step through and see what's happening.

**Comment by Skjalgsm** [comment]
Theres nothing in the Console in Unity.

I'll attach the debugger to Unity the next time it happens.

**Comment by van800** [comment]
Please reopen this, if it still appears

**Comment by Skjalgsm** [comment]
It still appears. How do I reopen?

**Comment by van800** [comment]
Yesterday fix https://github.com/JetBrains/Unity3dRider/commit/075cb8932679ac99dc6569be6adebd518e073327
might have fixed this also. Please try.

**Comment by Skjalgsm** [comment]
I've tried it and it still is not working 100% of the time.

**Comment by aaronjbaptiste** [comment]
Not working for me 100% of the time. Opening a C# script from Unity does not leave focus on Rider.

**Comment by van800** [comment]
@aaronjbaptiste Any errors in the log?
Could you please debug it? Set brakepoint in ActivateWindow.
Thanks!

**Comment by aaronjbaptiste** [comment]
No error logs, only this info:

(Log) [Rider] open -n ""//Applications/Rider EAP.app"" --args ""/Users/aaron/Documents/GameDev/MYMMOx/MYMMOx.sln"" -l -1 ""/Users/aaron/Documents/GameDev/MYMMOx/Assets/Libs/ParadoxNotion/NodeCanvas/Tasks/Actions/Movement/RotateTowards.cs""

The file opens in rider, but if I look at the current active window in the top OSX bar it switches to Rider then straight back to Unity.

I don't think ActivateWindow is called due to:

`if (new FileInfo(riderPath).Extension == ".exe")`

Probably should have mentioned i'm on latest macOS. It's possibly a bug in Rider itself, as I've played around with the code from the vsCode plugin which seems identical and that ide switches focus fine.

**Comment by van800** [comment]
@aaronjbaptiste Thanks for the info, I will try to solve it.

**Comment by aaronjbaptiste** [comment]
Another thing i've noticed when it tries opening Rider is that for a brief moment it opens a second instance of Rider, you can see it bobbing in the Dock. That one closes down within a second.

**Comment by aaronjbaptiste** [comment]
Removing -n from the open command correctly focusses the Rider app, but then the clicked file is not opened in Rider anymore.

**Comment by aaronjbaptiste** [comment]
I've managed to get it working by setting `proc.StartInfo.UseShellExecute = true;` however it does spit out an exception:

```
(Exc) InvalidOperationException: UseShellExecute must be false when redirecting I/O.
System.Diagnostics.Process.Start_shell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start()
```

Seems to be ok though?

**Comment by aaronjbaptiste** [comment]
Spoke too soon, line focus does not work

**Comment by van800** [comment]
With help of https://github.com/PotterDai/RiderUnity3DConnector/releases open file is fast and Rider is always focused after opening file. It needs to be installed manually in Rider via Settings->Plugins->Install plugin from disk.

Please try.

**Comment by aaronjbaptiste** [comment]
works great!
