### ISSUE TITLE
Doesn't work on OSX

### ISSUE THREAD

**Issue by hassankhan** [JetBrains/Unity3dRider#3]
I've installed the latest version of Rider on OSX, and followed the instructions.

When I click 'Open C# project', it launches both MonoDevelop and Rider. Rider gets stuck on the project selection screen, and MonoDevelop works as it usually does.

**Comment by dioteos** [comment]
The same issue. "Go To Declaration" also doesn't work

**Comment by van800** [comment]
@dioteos Please check project guids in the sln file.
It must be @"Project(""{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}"")";

@hassankhan 'Open C# project' may not work in OSX, please try to open any C# file from the project.

**Comment by hassankhan** [comment]
Works now, thanks!
