### ISSUE TITLE
Setting TargetFramework to v4.5 fails to compile with UniRx

### ISSUE THREAD

**Issue by Silphid** [JetBrains/Unity3dRider#33]
Hi!

I don't understand why the plugin forces the target framework version up to 4.5, not 3.5?  Unity targets 3.5, so setting it to 4.5 introduces compilation problems, as with UniRx, which relies on that information to determine whether to define its own IObservable<T> or to rely on the one introduced in .NET 4:

#if !NETFX_CORE
namespace UniRx
{
    public interface IObservable<T>
    {
        IDisposable Subscribe(IObserver<T> observer);
    }
}
#endif
 
When target framework is set to 4.5, I end up with ambiguous references to IObservable all over my code.

Every time I update the Rider integration plugin, I end up having to tweak RiderAssetPostprocessor.cs to set the target framework to "v3.5":

//      var version = new Version(targetFrameworkVersion.Value.Substring(1));
//      if (version < new Version(4, 5))
    targetFrameworkVersion.SetValue("v3.5");

Would there be a cleaner / more permanent way of dealing with this?

Thanks in advance!
Mathieu

**Comment by van800** [comment]
related to https://github.com/JetBrains/Unity3dRider/issues/9

**Comment by van800** [comment]
On mac and linux Rider uses msbuild under mono4 for compilation.
But mono 4 doesn't guarantee anything for dotnet < 4.5
http://www.mono-project.com/docs/about-mono/releases/4.0.0/
"We dropped support for the 2.0, 3.5 and 4.0 assemblies"
For example is causes https://youtrack.jetbrains.com/issueMobile/RIDER-573

**Comment by Silphid** [comment]
I'm developing on OS X, targeting iOS & Android, and using C# 6.0 (with CSharp60Support).

**Comment by Silphid** [comment]
OK, but I'm not sure I understand the consequences/implications.  Isn't Unity targeting .NET 3.5?  If we want the same compilation results in Unity AND Rider, shouldn't we use the same target version?

**Comment by van800** [comment]
One of the main pain points for the users was that mono4 doesn't have 3.5 dlls related to linq. They are just missing.

**Comment by van800** [comment]
Problem will go away when Unity migrates fully to mono4. But for now I will add a user setting for the plugin, so it will at least be possible to update without changing anything. I am not a fan of user settings, but I don't have better idea. Thank you for the request!

**Comment by Silphid** [comment]
Fully agree, not ideal, but would be greatly appreciated in the meantime! :)

Mono4 will be a real blessing when it finally makes it into Unity! :)

**Comment by van800** [comment]
22ba2db77873eef63569b78247b4aa321553ad85

**Comment by Silphid** [comment]
Thank you so much! :)
