### ISSUE TITLE
.gitignore issue of this repo itself.

### ISSUE THREAD

**Issue by zhuchun** [JetBrains/Unity3dRider#35]
Hi, I noticed gitignore has a line `*.meta`. This could cause potential risks if user ignore **How to use** and copy all files to their project, say losing any new script ref in their scenes afterward. So please cosider removing it.

This page explained why meta files should be added.
https://docs.unity3d.com/Manual/ExternalVersionControlSystemSupport.html

**Comment by van800** [comment]
@zhuchun 
not sure why, but vscode plugin also ignores *.meta
https://github.com/dotBunny/VSCode/commit/f0a2ef5881826474ab635859c2a3019af323722f

**Comment by zhuchun** [comment]
@van800 I see, however, I just experienced a ref lost problem a few days ago when I added `*.meta` into gitignore. Thus I'm sure it could happens. 

IMHO, there're a few reasons why people add it in public repos.

a) For game projects that are not using Git. They don't have to worry about meta problem, because they're hidden by default.

b) For repos that are not including demo example or their scripts don't have to be ref in any scene, their user also have a correct guide that prevent them from doing so.

**Comment by van800** [comment]
@zhuchun what if I add a unitypackage for plugin installation? Will it reduce the possibility of occasional adding gitignore to user project and resolve this request as well?

**Comment by zhuchun** [comment]
@van800 That sounds a good idea 👍 Put a unitypackage in Release, so beginners could have an option while this repo doesn't need to change.

**Comment by van800** [comment]
Release issued.
