### ISSUE TITLE
macOS Focus Problem

### ISSUE THREAD

**Issue by ssoher** [JetBrains/Unity3dRider#36]
If Rider is open in another macOS Space, upon double clicking an error in the Unity console, it translates to the main desktop instead of the Space where the Rider is.

**Comment by Dukobpa3** [comment]
Agree. Very annoying :)

**Comment by van800** [comment]
Could you please provide more info.
I got mac Sierra with three spaces.
Unity is in the space 2
Rider is in the space 3
Double click file in Unity just leaves Rider at the same space.
I tried with and without "Right click on its icon in the toolbar -> Options->Assing To ->This desktop"

**Comment by ssoher** [comment]
1) Open Rider, make it fullscreen in it's own space
2) Open Unity, make it fullscreen in it's own space
3) Open any script in the project with Rider, introduce an error
4) Let Unity compile the script, double click on the error in the console window

It will show the first space/desktop instead of going to Rider's space

**Comment by van800** [comment]
reproduced, thanks!
The workaround is to do the following "Right click on Rider in toolbar -> Options -> Assign To -> This desktop". This will force each new Rider instance to start in the same desktop.
It must be the same issue with MonoDevelop, is it?

**Comment by van800** [comment]
Proper fix, which comes in mind would require some inter process communication between UnityPlugin and Rider, so the plugin would just send a message to Rider to open something without the need to do Process.Start

**Comment by ssoher** [comment]
Thanks for the workaround! That fix sounds good.

**Comment by ssoher** [comment]
I haven't been using Monodevelop since it was first packaged with Unity, MD sucks.

**Comment by van800** [comment]
With help of RiderUnity3dConnector open file is fast and Rider is always focused after opening file. It needs to be installed manually in Rider via Settings->Plugins->Install plugin from disk.

Please try.

**Comment by ssoher** [comment]
Nice, I'll try it. Why not add it to the default repos so we can install it within Rider?

**Comment by van800** [comment]
@ssoher You are thinking the same direction as we do. Sooner or later plugins will be merged.

**Comment by ssoher** [comment]
@van800 so I've tried it. Installed RiderUnity3DConnector 1.2. Installed the latest version of this Unity plugin too. And I see CallUDPRider log in my console without any following errors. If Rider is closed, it does not start Rider. If Rider is open, it opens the file in Rider, Rider blinks in the taskbar but does not get any focus. Windows 10 x64.

**Comment by van800** [comment]
@ssoher Thanks! I figured out the problem "If Rider is open, it opens the file in Rider, Rider blinks in the taskbar but does not get any focus." and pushed the fix.
Let me share with you the details, so we check that everything is working as expected at your side.
So,
1. CallUDPRider is called everytime you open asset in Unity.
1.1. If Rider is started and the RiderUnity3DConnector is installed, it will be used to open solution and file and put carent to line.
1.2. If Rider is not started or RiderUnity3DConnector is not present, then there will be fallback to calling something like
"C:\Program Files (x86)\JetBrains\Rider 163.12645\bin\rider64.exe" "C:\Work\Unity3dRider\Unity3dRider.sln" -l 273 "C:/Work/Unity3dRider\Assets/Plugins/Editor/JetBrains/RiderPlugin.cs"
It will start Rider and open the file and put caret to line.

Thanks for your help!

**Comment by ssoher** [comment]
Amazing, thanks @van800 !

**Comment by ssoher** [comment]
@van800 I just had the chance to try this on macOS, sorry for the late reply on a closed issue, but one problem still persists.

Rider still does focus on the first macOS Space if the Rider is set to fullscreen. (Not windowed in another space but completely fullscreen). If Rider is "assign to this desktop" -ed it runs in a window and not in fullscreen which is a problem especially on small Macbook Air screens.

- Set Rider to fullscreen
- Open any script in Unity through the Project window or an error/warning in the console
- macOS shows the blank main space instead of the fullscreen Rider space

**Comment by van800** [comment]
@ssoher could you please try the most recent plugin, implementation of opening file, when Rider is already running was changed. Maybe focus problem is also fixed?

**Comment by ssoher** [comment]
@van800 works just fine now, great job, thanks!
