### ISSUE TITLE
Go To Line & Column From Errors

### ISSUE THREAD

**Issue by ssoher** [JetBrains/Unity3dRider#39]
Currently Rider moves the caret to the line where the error is when the error log is double clicked in Unity. Unity reports both the line and the column where the error is. Is it possible for Rider to move to the correct column too? 

It's not that important, just VS does it and it feels more convenient.

**Comment by van800** [comment]
Good request, but unfortunately public API for all editors (except VS) provides only line number.
bool OnOpenAsset(int instanceID, int line)

Apparently VS has got specific support.
