### ISSUE TITLE
Cannot generate .sln & .csproj files for new Unity3D project

### ISSUE THREAD

**Issue by wizcas** [JetBrains/Unity3dRider#4]
.sln & .csproj files are often not included in a Unity3D git repo. After cloning a repo, it is impossible to open code files by Rider. Rider will tell you that the solution file cannot be found. I had to switch back to MonoDevelope, reopen a code file to generate a solution file, and switch to Rider again to make it work.

Could you please add the feature of generating solution files?

**Comment by van800** [comment]
If you have a projet opened in Unity - it will do the job to generate solution.
Otherwise it is a request to Rider https://youtrack.jetbrains.com/issues/RIDER/
not the Unity plugin.
