### ISSUE TITLE
Rider does not automatically delete .meta files when a file is deleted

### ISSUE THREAD

**Issue by orkunozbek** [JetBrains/Unity3dRider#41]

**Comment by citizenmatt** [comment]
This is probably best reported to the [resharper-unity](https://github.com/JetBrains/resharper-unity) repo. This repo is more about making sure Unity can open projects in Rider, while resharper-unity is about providing Unity specific functionality in Rider and ReSharper. There is, in fact, already an issue - JetBrains/resharper-unity#61.

**Comment by orkunozbek** [comment]
thanks @citizenmatt
