### ISSUE TITLE
Request is not supported by the protocol version

### ISSUE THREAD

**Issue by kolombet** [JetBrains/Unity3dRider#42]
Using Rider1.0EAP with unity 5.2.3p3

When trying to see simple variable content when debugging, all works fine. When want to see content of complex structure, like List<T>, got error:

"This request is not supported by the protocol version implemented by the debuggee."

**Comment by van800** [comment]
Request moved to https://youtrack.jetbrains.com/issue/RIDER-3767
Thanks!
