### ISSUE TITLE
impossible to run unit tests from Rider

### ISSUE THREAD

**Issue by andrew-klepcha** [JetBrains/Unity3dRider#43]
may be this is relates to rider-unity integration?
description: https://youtrack.jetbrains.com/issue/RIDER-3288

please pay attention at: https://youtrack.jetbrains.com/issue/RIDER-3288#comment=27-1777347

**Comment by van800** [comment]
Please let me know, if it helped. Thanks!

**Comment by andrew-klepcha** [comment]
Now I don't see any error or fail message but it seems test running not work correctly :(
![unittestsrider](https://cloud.githubusercontent.com/assets/10937430/21452874/ff7d8e1e-c91a-11e6-9218-10b70b7f9566.png)
![unittestsu3d](https://cloud.githubusercontent.com/assets/10937430/21452873/ff7d23e8-c91a-11e6-85bd-40b9925bddf8.png)

**Comment by andrew-klepcha** [comment]
can I help with some debug, log or other information?

**Comment by van800** [comment]
@andrew-klepcha your OS?

**Comment by andrew-klepcha** [comment]
Linux:
klepcha@klepcha-lnx ~ $ uname -a
Linux klepcha-lnx.awem.local 4.4.21-std-def-alt0.M80P.1 #1 SMP Mon Sep 19 08:54:36 UTC 2016 x86_64 GNU/Linux

mono:
klepcha@klepcha-lnx ~ $ mono -V
Mono JIT compiler version 4.6.2 (tarball Tue Nov 29 18:21:02 MSK 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

Unity: 5.5.0xf3Linux

Rider:
Rider 1.0 EAP
Build #RS-163.10479, built on December 19, 2016
Rider EAP User
Expiration date: January 18, 2017
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by van800** [comment]
please try again with https://github.com/JetBrains/Unity3dRider/commit/6804d583ca8511155ae49500d9df7c5d73e64401

**Comment by andrew-klepcha** [comment]
now it works :)
Thanks!!!
