### ISSUE TITLE
Need better output if Rider was installed to different location and Unity3dRider doesn't find it

### ISSUE THREAD

**Issue by sionzeecz** [JetBrains/Unity3dRider#44]
Hi, is possible to open project without welcome screen? 
Every project have .sln file, why is still here welcome screen?

Welcome screen = Screen where user can select between projects.

Approach:
1. Exit Rider
2, Open Unity Editor with your own Project
3, Open anyone Script
4, Do this same with another one project. 
5. Exit Rider
6. Open any Unity Project
7. Open Script
And it show welcome screen now where you can select between project 1 & 2.

**Comment by van800** [comment]
Any logs by the plugin in Unity?

**Comment by sionzeecz** [comment]
Using latest version of Unity (beta) and latest version of this plugin.
![Unity Log](https://ctrlv.cz/shots/2016/12/31/oFEZ.png)
![Welcome Screen Image](https://ctrlv.cz/shots/2016/12/31/cSts.png)

**Comment by van800** [comment]
What is your OS and Unity version? It seems that plugin is not fully operable at your environment ( maybe onopenasset doesn't fire). I need to check.

**Comment by sionzeecz** [comment]
Unity Pro 5.6.0b3 (64bit),
Windows 10 Pro (64bit) (version 1607, build 14393.576)

**Comment by van800** [comment]
Do both projects have this plugin?

**Comment by sionzeecz** [comment]
Yes, exactly this

**Comment by van800** [comment]
I am trying to follow your steps:
1. Exit Rider (ok)
  2, Open Unity Editor with your own Project 
(output - several lines in the log [Rider] Post-processing C:\Work\Unity3dRider\Assembly-CSharp-Editor-firstpass.csproj)
  3, Open anyone Script
(output - [Rider] "C:\Program Files (x86)\JetBrains\Rider 163.10479_1\bin\rider64.exe" "C:\Work\Unity3dRider\Unity3dRider.sln" -l -1 "C:/Work/Unity3dRider\Assets/NewBehaviourScript.cs")
  4, Do this same with another one project.
Do you mean "Close project 1" and "Open project 2"?
(output - several lines in the log [Rider] Post-processing C:\Work\Unity3dRider2\Assembly-CSharp-Editor-firstpass.csproj)
2.Exit Rider (ok)
3. Open any Unity Project
We already did "Open project 2". Not sure.
(output - several lines in the log [Rider] Post-processing C:\Work\Unity3dRider2\Assembly-CSharp-Editor-firstpass.csproj)
4. Open Script
(output - [Rider] "C:\Program Files (x86)\JetBrains\Rider 163.10479_1\bin\rider64.exe" "C:\Work\Unity3dRider2\Unity3dRider.sln" -l -1 "C:/Work/Unity3dRider2\Assets/NewBehaviourScript.cs")

Does it seem right? What are the differences with your repro?

**Comment by sionzeecz** [comment]
Interesting, when you open project you have got debug about opened file. 
I see only debug about .csproj files.

I created new project, copied plugin inside it. 
Assets -> Open C# in Rider and it throwed: 
`Win32Exception: ApplicationName='C:\Program Files (x86)\JetBrains\Rider 163.8671\bin\Rider64.exe', CommandLine='"D:\PROJECTS\Sionzee\TestProject\TestProject.sln"', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
Assets.Plugins.Editor.JetBrains.RiderPlugin.CallRider (System.String riderPath, System.String args) (at Assets/Plugins/Editor/JetBrains/RiderPlugin.cs:157)
Assets.Plugins.Editor.JetBrains.RiderPlugin.MenuOpenProject () (at Assets/Plugins/Editor/JetBrains/RiderPlugin.cs:206)
`
Then I created random scripts, opened it by double click on him.
It opened Rider with layout, closed and showed 'Welcome to Rider'
Where is not new project in project list. I have to click on Open Solution and find mine .sln file

Here is full editor log. [Pastebin](http://pastebin.com/WAzGD7L8)

**Comment by van800** [comment]
Please also check that both exe and sln files exist

**Comment by van800** [comment]
If the path to Rider64.exe is not correct - open Unity Preferences ->External Script Editor ->Browse

**Comment by sionzeecz** [comment]
Yes! You're right. But how it opened Rider in incorrect place?
Now it works correctly, but will be great if you say something about it in readme. 
Like something: Do not forget after update Rider to again choose correct path to Rider EAP directory in Preferences. Anyway, thanks you for help.

**Comment by van800** [comment]
Actually there is code, which (only for Windows) tries to help with this problem. Determine new Rider64.exe path and update Unity setting EditorPrefs.SetString("kScriptsDefaultApp", newPath); line 81 in RiderPlugin.cs
But it didn't work in your case for some reason. It would be cool to understand, what was so specific in your case. 

Specifically, what were the previous path and the new one?

Thanks!

**Comment by sionzeecz** [comment]
The previous path was on another disk partition. 
I installed new version on the second hard drive. 

Same path but another version in directory name.

**Comment by van800** [comment]
%userprofile%\.Rider10\system\.home can be used to determine Rider location.
