### ISSUE TITLE
Constantly showing up "update 'External Script Editor' path"

### ISSUE THREAD

**Issue by Garfeild** [JetBrains/Unity3dRider#49]
Hello, I'm using Rider EAP for a while with Unity3d. After last plugin update I'm facing issue with constantly showing up message "Please update 'External Script Editor' path to JetBrains Rider." I've tried to debug this issue by myself and it seems that check in `CallRider` doesn't work properly. Also, I've prepared pull request with changes.

OS: OS X 10.11.6
Rider EAP Version: 
Rider 1.0 EAP
Build #RS-163.12057, built on January 17, 2017
Rider EAP User
Expiration date: February 16, 2017
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by van800** [comment]
Pull request merged. Thank you!
