### ISSUE TITLE
Error trying to open files

### ISSUE THREAD

**Issue by alanweing** [JetBrains/Unity3dRider#51]
Hi!

Every time I try to open a file in unity I get the message showed in the attached image. I did a complete reinstall on rider and unity but nothing changed.

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/15879871/22432227/6273e29a-e6fb-11e6-8d36-cba1e50992a3.png)

**Comment by van800** [comment]
It is the same as here, one of the latest comments.
https://youtrack.jetbrains.com/issueMobile/RIDER-3377
Please comment and attach Rider logs.

**Comment by alanweing** [comment]
Thanks for the reply!

I don't have access to the link you provided, even with my account from JetBrains.
The logs are attached below; the ones not included were empty.

[backend.out.log.txt](https://github.com/JetBrains/Unity3dRider/files/739949/backend.out.log.txt)
[frontend.log.txt](https://github.com/JetBrains/Unity3dRider/files/739948/frontend.log.txt)
[frontend-append.log.txt](https://github.com/JetBrains/Unity3dRider/files/739950/frontend-append.log.txt)
[backend.log.txt](https://github.com/JetBrains/Unity3dRider/files/739951/backend.log.txt)

**Comment by van800** [comment]
From what I see in the logs, it seems that Rider starts with commandline, which doesn't contain path to solution. Could you check please? Process Explorer should show it. Please also copy-paste the plugin logs from Unity console window, if there are at least something.

**Comment by alanweing** [comment]
Hi! Sorry for the delay.

The console window, from Unity, have nothing. 
I'm attaching a print from the Process Explorer showing the details about Rider. 

![image](https://cloud.githubusercontent.com/assets/15879871/22468398/46d7d320-e7af-11e6-9a4b-31b87f2b6634.png)

**Comment by van800** [comment]
I see, do you really have the Unity3dRider in your project?
From the readme.md:
Install the plugin into your project
    Copy the folder Assets/Plugins/Editor/JetBrains from this repository into Assets/Plugins/Editor/JetBrains in your project.

**Comment by van800** [comment]
Once plugin is installed - you will see Rider tab in the Settings page
![image](https://cloud.githubusercontent.com/assets/1482681/22469247/a13ffdf8-e7cb-11e6-8076-18152e1e45eb.png)

**Comment by alanweing** [comment]
I don't know what happened, the first time I did this, I followed all the steps through and it didn't work. Now that I deleted everything and imported again, it worked!

Sorry for this, but it didn't work in the first time.
Thanks for your time!
