### ISSUE TITLE
Socket error or no response. Have you installed RiderUnity3DConnector in Rider?

### ISSUE THREAD

**Issue by PhilippCh** [JetBrains/Unity3dRider#52]
**Rider EAP version:** #RS-163.12057
**Unity version:** 5.5.0f3
**OS version:** OSX 10.11.5

I was wondering why it always took so long to load any file in Rider after clicking on it in Unity and noticed this warning in the editor console:

`[Rider] Socket error or no response. Have you installed RiderUnity3DConnector in Rider?`

The source code says Rider should be listening on UDP 11234, right? On my machine, `lsof -Pan -p $PID -i` where $PID is the Rider PID outputs a few TCP connections, but not the specified port. Did this change by any chance?

I have the plugin installed in Unity as well as installed ReSharper for Unity in Rider.

**Comment by van800** [comment]
Please search for RiderUnity3DConnector in the readme.md and follow the instructions. We have plans to merge plugins soon.
