### ISSUE TITLE
Firebase + UniRX ambiguous reference 

### ISSUE THREAD

**Issue by pwnpwn** [JetBrains/Unity3dRider#58]
As stated in the plugin file:
"- Without 4.5:
    - Rider will fail to resolve System.Linq on Mac/Linux
    - Rider will fail to resolve Firebase Analytics.
 - With 4.5 Rider will show ambiguos references in UniRx."

In our case we are using both UniRX and firebase analytics. As recommended we use target 4.5, but it is a hassle when trying to use UniRX for firebase tasks. Being fairly new to c# I've failed to find a solution for this. Is there any kind of temporary work around to avoid the ambiguous references? (We do not want to adopt target 6 just yet).

Any kind of help would be appreciated. 
Btw, Rider is just great and has made Unity fun to work with again!

**Comment by van800** [comment]
Can you share some small solution, which shows a problem with me? Thanks!

**Comment by van800** [comment]
#33 #20

**Comment by pwnpwn** [comment]
Here:
https://github.com/pwnpwn/unirx-firebase-issue

I created a new project, added the very same dependencies and the rider plugin. I get ambiguous reference in "Test.cs" when using rider, but not with vs code or monodevelop.

**Comment by van800** [comment]
Modern Rider build resolves Linq and Firebase Analytics with TargetFramework 3.5 just fine.
UniRx with 4.5 is still a problem unless UniRx namespace is added to every IObservable usage.
