### ISSUE TITLE
structs constructor are marked as errors

### ISSUE THREAD

**Issue by Souk21** [JetBrains/Unity3dRider#6]
```
public struct Breaks {
    public float Force { get; private set; }

    public Breaks (float force) {
        this.Force = force;
        }
}
```

Rider says I have to initialize my struct first like so :

```
public struct Breaks {
    public float Force { get; private set; }

    public Breaks (float force) : this() {
        this.Force = force;
        }
}
```

But unity builds my first example just fine.

Latest version of Rider and Plugin

**Comment by van800** [comment]
It looks like the difference between mono and .net
In VS12 or msbuild12 it doesn't compile, but in xbuild12 it compiles.
Not sure, what can be done about it.

**Comment by Souk21** [comment]
What is strange is that it started happening approximatively two releases ago (I think). Before that, it was not marked as an error.

**Comment by van800** [comment]
Workaround is to allow C# 6 by QuickFix . But it will allow all C#6 features, which may be even worse.
So maybe two releases ago C# 6 features were enabled.

**Comment by van800** [comment]
still an issue, at least till everybody migrate to NET4.6

**Comment by van800** [comment]
If it is still an issue - please create a new one in https://github.com/JetBrains/resharper-unity
