### ISSUE TITLE
Error in Unity projects for Unity 4.x

### ISSUE THREAD

**Issue by adamgit** [JetBrains/Unity3dRider#61]
Clean install in Unity 4.6.5, I get the following error message as soon as I copy this plugin into an empty project:

Assets/A External Plugins/JetBrainsRider/Editor/RiderAssetPostprocessor.cs(225,32): error CS0117: `UnityEditor.PlayerSettings' does not contain a definition for `GetApiCompatibilityLevel'

Rider (build 4089) then crashes with:

Fatal error initializing 'com.jetbrains.resharper.ideaInterop.vfs.VfsWriteOperationsHost'

Using Unity to do a "resynch with MonoDevelop" gets the project to open in Rider. Looking through the source code, it seems to me that Unity3dRider has multiple bugs here:

Firstly, the method call you're using doesn't even exist in Unity less than v5 - so you shouldn't be calling it to check whether you're in v4 or not.

Secondly, the output of the method call is an enum, which doesn't have strict numerical values - you should be comparing to the ENUM named values, not to an int.

**Comment by van800** [comment]
feel free to try the fix

**Comment by adamgit** [comment]
Would it work to use the UNITY_5_0_OR_NEWER #ifdef here? That's supposed to map to all versions of Unity >= 5.0

**Comment by adamgit** [comment]
I hit another problem where Rider won't save files when running with Unity 4.6 - it silently refuses to save, with no error reported.

So I've gone back to a 5.x project for now, to check if the bug is latest Rider, or something specific to 4.6 integration. So far, 5.x projects seem to be working fine.

But I'll come back and try the patch here next time I'm on the 4.6 project - thanks

**Comment by van800** [comment]
I used Unity 4.7 to investigate and fix the initial problem that you have reported.
And for that fix Rider saved the changes just fine.
If you ever see not-saving problem again - zip the logs from Help->Show log in Files, create a youtrack.jetbrains.com issue and let me know the issue number.
Thank you for the feedback.
