### ISSUE TITLE
Target 2.0 to fix scripts imported for compatibility

### ISSUE THREAD

**Issue by doctorpangloss** [JetBrains/Unity3dRider#62]
I've unchecked the Target 4.5 preference and `System.Linq` works and imports just fine. With the preference checked, I can't provide my own implementation for e.g. `System.Tuple` (I copy and paste the one from Mono), because there's a conflict. I think a lot of Unity projects rely on these compatibility stubs, but Rider will incorrectly interpret them because it thinks it's at a higher framework level than Unity actually when using 4.5.

According to a comment here,
https://github.com/JetBrains/Unity3dRider/blob/master/Assets/Plugins/Editor/JetBrains/RiderPlugin.cs#L309 , there's an issue documented with targeting `3.5`/`2.0` instead of `4.5`. Is this still true?

**Comment by van800** [comment]
@doctorpangloss what is your OS and mono version? Thanks!
