### ISSUE TITLE
Proposal: Changing the structure of this plugin

### ISSUE THREAD

**Issue by schloepke** [JetBrains/Unity3dRider#63]
**Proposal:** Currently the structure of this plugin is a full Unity project sort of. It would be better to only have the JetBrains folder under version control so that it is possible to integrate the plug in as a submodule. Alternatively adding it to the Unity Asset Store is also an option (and would mean that it should use a similar file structure).

**Comment by citizenmatt** [comment]
The ultimate plan is that this plugin becomes part of Rider's own support, currently living in the [JetBrains/resharper-unity](https://github.com/JetBrains/resharper-unity) repo. One option is that Rider will prompt you to add any source files to a project that doesn't already have it added, and should make installing the various plugins a lot easier.

**Comment by Lattyware** [comment]
For what it's worth, while this should be fixed by being handled as @citizenmatt mentioned in his comment, you can use this as a submodule right now - we've been doing it, and while it does mean it's under a dumb folder hierarchy, that doesn't really matter and it works.

**Comment by van800** [comment]
Next Rider EAP build will come with new resharper-unity plugin, which has UnityPluginInstaller
it will put 2 files of Unity3dRider into project automatically to Assets\Plugins\Editor\JetBrains.
I guess this will be comfortable.
