### ISSUE TITLE
Opening files in Unity not opened in an already running rider

### ISSUE THREAD

**Issue by schloepke** [JetBrains/Unity3dRider#64]
First time I click a C# file opens rider and also the file I clicked. Now that rider is already running in the background this doesn't work anymore. I double click a C# file in Unity and it brings Rider to the front but doesn't open the file I clicked. It just acts like switching the application. I haven't looked into the issue much jet but a quick look into the plugin tells me that it may works calling rider directly and doesn't work using the UDP connection.

The error occurs on OSX and I haven't testet it on Windows yet. Also if the file is already opened in Rider it doesn't get the focus either. Looks pretty much that rider is not aware of the file to be shown.

Double clicking on an error however seems to work even with an already opened rider.

I will add more infos when I have the time to look into the issue a bit more.

**Comment by van800** [comment]
Please paste here output from Unity.
Attach to Unity with Rider, put brakepoint to OnOpenedAsset method and double-click script in Unity should help to understand what happens.
Thanks for reporting

**Comment by schloepke** [comment]
Ok I have investigated in this problem a bit more.

1. The problem is only under OSX. Windows works.
2. The problem only appears if the "Rider Unity3D Connector" is not installed or deactivated

On Windows it works without the rider unity3d connector. In OSX it doesn't. The plugin calls

    open -n "//Users/stephan/Applications/JetBrains Toolbox/Rider.app" --args "/Users/stephan/test-project/test-project.sln" -l -1 "/Users/stephan/test-project/Assets/CharacterControl/Scripts/MMOAvatarMovement.cs"

If this line is called the first time it opens Rider and navigates to the file. However if the open is called again OSX recognises that rider is already running and switches to it. Here Rider seems to ignore the command line or OSX isn't passing it to the application.

From my point of view a note that on OSX the RiderUnity3DConnector has to be installed would be nice in the installation (and on windows it is recommended). The issue is not an issue or it is an issue for Rider rather than this plugin so I close the issue since it works as required.

Sorry about that!

**Comment by citizenmatt** [comment]
@van800 Can you reopen this, please? I'm seeing the same issue on macOS. Double clicking a file won't open it in Rider EAP21. I'll try and investigate.

**Comment by van800** [comment]
@citizenmatt please try my last commit. it removes the need to install RiderUnity3dConnector.

**Comment by schloepke** [comment]
I updated to the latest commits and removed RiderUnity3dConnector. Now opening rider first time works but trying to open a file now does nothing. Neither the file is opened in rider nor the focus is changed to rider. So its worth than before on macOS (Not tested under Windows yet). I attach a log file of Unity even it doesn't show anything interesting.

I have looked into the WebClient call and it doesn't return with an error but the returned content is also empty which I think is expected. Trying to call the URL directly with curl results in a security dialog in Rider asking me to allow the request. If I press yes the file is indeed shown and the curl caller receives a 200 OK with empty content. When I deny the request however I get the same only now a header is set that I was blocked but still 200 OK and empty content.

Also I noticed that in the plugin there is a method Log which delegates to Debug.Log of Unity. Like in most Java logging frameworks this delegation means that every log statement is shown as coming from that delegation method. It is better to call Debug.Log("[Rider] ...") directly rather than delegate the call so that in the log the line number from the logging trigger is correct.

[RiderUnityPluginLog.txt](https://github.com/JetBrains/Unity3dRider/files/974160/RiderUnityPluginLog.txt)

**Comment by citizenmatt** [comment]
Looks like the macOS `Uri` constructor is unescaping the path. It's going from `/api/file//Users/...` to `/api/file/Users/...` and I don't think IntellIJ likes that. I'll keep digging...

**Comment by van800** [comment]
Logs states: 
21:45:35.657 | WARN  | RestService                    | File "/home/ivan/Work/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs" not found

and the file is present, so must be something different.

**Comment by citizenmatt** [comment]
I get the same warning, but without the leading `/`:

> 21:04:37.329 | WARN  | RestService                    | File Users/matt/UnityProjects/GemShader/Assets/GemExample/Scripts/Things/Orbit.cs not found

But you can use query string parameters, too, so changing the url to this works on Mac:

```cs
var url = string.Format("http://localhost:63342/api/file?file={0}{1}", filePath, line < 0 ? "" : "&line=" + line);
```

**Comment by van800** [comment]
@citizenmatt Thanks! I missed this possibility.

**Comment by citizenmatt** [comment]
I tried pushing an update, but don't have permissions.

**Comment by schloepke** [comment]
I tested it on my mac and it works now. One thing I noticed still though is that double clicking on an already opened file doesn't jump to the last cursor position but instead always to line 1. The problem here is the call which always attaches a line=0 at the end. When you look at the code:
`var url = string.Format("http://localhost:63342/api/file?file={0}&line={1}", filePath, line < 0 ? 0 : line);`
You see it is different from what @citizenmatt was suggesting:
`var url = string.Format("http://localhost:63342/api/file?file={0}{1}", filePath, line < 0 ? "" : "&line=" + line);`
The second version does correctly work without &line=0 but instead it works not at all. So from my point of view there needs to be an issue request to Rider that lines less than or equal to zero will result in staying in the already opened line.

**Comment by van800** [comment]
@schloepke Thanks for the info.
I did try the @citizenmatt suggestion, but it was not working for me.
I will recheck tomorrow again.
And even more fun is that on Windows url with parameters didn't work for me now, so I would need to set separate url for it.

**Comment by van800** [comment]
https://youtrack.jetbrains.com/issue/IDEA-172344
https://youtrack.jetbrains.com/issue/IDEA-172350

**Comment by van800** [comment]
For now I pushed 2 different urls for windows and mac.
The only problem without workaround RIDER-6092 - on mac opening file without line will drop caret to 0 offset.

**Comment by schloepke** [comment]
Possible merge issue #66 in here since it is an error occurring related to the changes of the ticket.

An idea would be to add the old RiderUnity3dConnector support as an configurable access. So we could select in the configs to either use the UDP/Connector way or the nativ HTTP way.
