### ISSUE TITLE
Remove informational console logging

### ISSUE THREAD

**Issue by richkzad** [JetBrains/Unity3dRider#67]
Using the plugin, there are several "[Rider] ..." messages that appear in Unity's console, but they don't seem very helpful, and just cause clutter.

It would be nice to remove all the logging that isn't important.

**Comment by van800** [comment]
https://github.com/JetBrains/Unity3dRider/commit/6ecccc5e3da52069a32e78e7a6d8d5c12ab034e6

**Comment by richkzad** [comment]
Great, thank you!
