### ISSUE TITLE
Auto-switch project when opening a file from Unity

### ISSUE THREAD

**Issue by richkzad** [JetBrains/Unity3dRider#70]
I've been switching between different projects in Unity recently, and noticed that if I open a C# file from Unity, Rider will just open that file it within whichever project it already had open.

It would be nice if Rider was able to be sure the correct Unity project was open, or at least give me the option of switching to the new project.

**Comment by van800** [comment]
Thanks for requesting this. It will require changes both here and in https://github.com/JetBrains/resharper-unity.

**Comment by van800** [comment]
I am closing this request, please follow https://github.com/JetBrains/resharper-unity/issues/266
