### ISSUE TITLE
File opens in Webstorm and not in Rider

### ISSUE THREAD

**Issue by z3ntu** [JetBrains/Unity3dRider#71]
When I double-click a file in Unity and have `rider.sh` set in the "External tools" window, the file opens in Webstorm. It doesn't matter if Rider is already running or not. Note, that when I close Webstorm and double-click a file, Rider opens as expected.

Video demo: https://youtu.be/FBUytBIfMJc

**Comment by van800** [comment]
Thanks for the info.

**Comment by van800** [comment]
141374340ff894777062875dbfab4ac89649a927

**Comment by van800** [comment]
Please try

**Comment by z3ntu** [comment]
Yes, now Rider opens with the file even though Webstorm was already open 👍 Thanks for the fix!
