### ISSUE TITLE
Unity 2017.1.0b5 includes some JetBrains Rider support

### ISSUE THREAD

**Issue by van800** [JetBrains/Unity3dRider#73]
It has got the following features:
.sln and csproj generation:
- Set LangVersion
- Added <TargetFrameworkVersion>v4.5</TargetFrameworkVersion> instead of v3.5 when Rider selected as script editor.
- Added unsafe. Always added as we now always compile with unsafe in the Editor.
- Parse defines from mcs.rsp and add them the .csproj files

Detecting and opening Rider:
- Detecting the following filenames as Rider: Rider.exe, Rider32.exe, Rider64.exe, Rider EAP.app, Rider.app, rider.sh
- Opening Rider with: "<.sln path>" -l <line number> "<script path>"

**Comment by van800** [comment]
Unity3dRider still make useful work:
1. Supports older Unity versions
2. Workarounds https://youtrack.jetbrains.com/issue/RIDER-6354
3. Calls Rider http api for fast navigation to file and line.
4. On Windows helps update path to Rider, if other version of Rider was installed.
5. Sets TargetFramework back to v3.5, if specified in Unity3dRider  settings.

**Comment by dogfuntom** [comment]
Why v4.5 instead of v3.5?

**Comment by van800** [comment]
Rider can only use mono >=4. And in mono 4 framework 3.5 is not supported.
