### ISSUE TITLE
SocketException: Connection refused when opening file

### ISSUE THREAD

**Issue by Bartwillemsen** [JetBrains/Unity3dRider#74]
Hi!

I just installed the latest version of Rider (EAP 22). Currently when I try to open a file by clicking on it in the Unity Editor, I get this error (stack trace included): 

```
SocketException: Connection refused
System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP, Boolean requireSocketPolicy)
System.Net.WebConnection.Connect (System.Net.HttpWebRequest request)
Rethrow as WebException: Error: ConnectFailure (Connection refused)
System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult)
System.Net.HttpWebRequest.GetResponse ()
System.Net.WebClient.GetWebResponse (System.Net.WebRequest request)
System.Net.WebClient.DownloadDataCore (System.Uri address, System.Object userToken)
UnityEditor.DockArea:OnGUI()
```
I'm running the latest version of Unity, Rider and this plugin.

**Comment by van800** [comment]
Is it full stacktrace?
Could you please attach all output from Unity console and zip with all Rider logs (Help->Show log in Files)
Thansk!

**Comment by Bartwillemsen** [comment]
Sure, I am sorry! I included all the log files in the following zip.
[Rider logs.zip](https://github.com/JetBrains/Unity3dRider/files/1021628/Rider.logs.zip)

**Comment by van800** [comment]
Sorry, I forgot to ask you enable Unity3dRider logs in Unity->Preferences->Rider.

**Comment by Bartwillemsen** [comment]
Woops. forgot you guys disabled logging by default! Finally, this is all the output I get when I click on a C# file in the Unity project view.
[Unity3DRider_log.txt](https://github.com/JetBrains/Unity3dRider/files/1021896/Unity3DRider_log.txt)

**Comment by van800** [comment]
Exception doesn't seem to be related to the Unity3dRider plugin.
You may try to comment everything in DetectPortAndOpenFile except return false; and check if exception remain.

**Comment by Bartwillemsen** [comment]
I did just notice that opening a file while Rider is already running doesn't throw that exception, and the file is opened correctly in Rider.

Commenting out the mentioned code causes the issue to also disappear actually!

**Comment by van800** [comment]
Please try the branch https://github.com/JetBrains/Unity3dRider/commits/webclient

**Comment by Bartwillemsen** [comment]
Hi! I tried that branch but it doesn't fix the issue.

**Comment by mpaleo** [comment]
Same problem here

**Comment by van800** [comment]
I have reproduced also. Investigating

**Comment by van800** [comment]
fix is in the branch https://github.com/JetBrains/Unity3dRider/commits/lnktopath 
Operable, but not yet fully finished and tested everywhere.

**Comment by Bartwillemsen** [comment]
Thanks, I'll try that branch as soon as possible. If there is anything I can help with, or try in particular please tell!

**Comment by van800** [comment]
Must be fixed with merge of lnktopath https://github.com/JetBrains/Unity3dRider/commit/02b0c958527297fe072756849c98f2805ed39cf1

**Comment by van800** [comment]
Please try and follow up with results. Thanks!

**Comment by Bartwillemsen** [comment]
Jsut tried it and everything works like a charm again. :) Thanks for the fix!
