### ISSUE TITLE
SystemInfo.operatingSystemFamily does not exist in Unity 5.4.4f1

### ISSUE THREAD

**Issue by Skjalgsm** [JetBrains/Unity3dRider#75]
Theres a compile error in RiderPlugin.cs as SystemInfo.operatingSystemFamily does not exist on Unity 5.4.4f1.

I propose that you change it to use SystemInfo.operatingSystem which returns a string instead

**Comment by Skjalgsm** [comment]
`/// <summary>
    /// Other,
    /// MacOSX,
    /// Windows,
    /// Linux,
    /// </summary>
    /// <returns></returns>
    public static int GetOperatingSystemFamily()
    {
#if UNITY_5_5_OR_NEWER
			return (int) SystemInfo.operatingSystemFamily;
#else
      if (SystemInfo.operatingSystem.StartsWith("Mac", StringComparison.InvariantCultureIgnoreCase))
      {
        return 1; //Mac
      }
      if (SystemInfo.operatingSystem.StartsWith("Win", StringComparison.InvariantCultureIgnoreCase))
      {
        return 2; //Windows
      }

      return 0; //Other
#endif
    }

    private static string GetDefaultApp()
    {
        var alreadySetPath = EditorPrefs.GetString("kScriptsDefaultApp");
        if (!string.IsNullOrEmpty(alreadySetPath) && alreadySetPath.ToLower().Contains("rider") &&
            RiderPathExist(alreadySetPath))
          return alreadySetPath;

        switch (GetOperatingSystemFamily())
        {
          case 2:
            //"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\JetBrains\*Rider*.lnk"
            //%appdata%\Microsoft\Windows\Start Menu\Programs\JetBrains Toolbox\*Rider*.lnk
            string[] folders = {@"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\JetBrains", Path.Combine(
              Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
              @"Microsoft\Windows\Start Menu\Programs\JetBrains Toolbox")};

            var newPathLnks = folders.Select(b=>new DirectoryInfo(b)).Where(a => a.Exists).SelectMany(c=>c.GetFiles("*Rider*.lnk"));
            if (newPathLnks.Any())
            {
              var newPath = newPathLnks.Select(newPathLnk=> new FileInfo(ShortcutResolver.Resolve(newPathLnk.FullName))).OrderBy(a => FileVersionInfo.GetVersionInfo(a.FullName).ProductVersion).LastOrDefault();
              if (!string.IsNullOrEmpty(newPath.FullName))
              {
                if (EnableLogging) Debug.Log("[Rider] " + string.Format("Update {0} to {1} product version: {2}", alreadySetPath, newPath, FileVersionInfo.GetVersionInfo(newPath.FullName).ProductVersion));
                EditorPrefs.SetString("kScriptsDefaultApp", newPath.FullName);
              }
            }
            break;

          case 1:
            // "/Applications/*Rider*.app"
            //"~/Applications/JetBrains Toolbox/*Rider*.app"
            string[] foldersMac = {"/Applications",Path.Combine(Environment.GetEnvironmentVariable("HOME"), "Applications")};
            var newPathMac = foldersMac.Select(b=>new DirectoryInfo(b)).Where(a => a.Exists)
              .SelectMany(c=>c.GetDirectories("*Rider*.app")).OrderBy(a => FileVersionInfo.GetVersionInfo(a.FullName).ProductVersion).LastOrDefault();
            if (newPathMac != null)
            {
              if (!string.IsNullOrEmpty(newPathMac.FullName))
              {
                if (EnableLogging) Debug.Log("[Rider] " + string.Format("Update {0} to {1}", alreadySetPath, newPathMac));
                EditorPrefs.SetString("kScriptsDefaultApp", newPathMac.FullName);
              }
            }           
            break;
        }

        var riderPath = EditorPrefs.GetString("kScriptsDefaultApp");
        if (!RiderPathExist(riderPath))
        {
          EditorUtility.DisplayDialog("Rider executable not found",
            string.Format(@"Rider was not found in {0}{1}Please update 'External Script Editor'.", riderPath,
              Environment.NewLine), "OK");
        }

        return riderPath;
    }`

**Comment by van800** [comment]
Thanks for the heads up. Fix pushed.
