### ISSUE TITLE
Why targeting framework 4.5 while Unity targets 3.5?

### ISSUE THREAD

**Issue by Silphid** [JetBrains/Unity3dRider#9]
First, thanks a lot for the plugin! :)

FYI, not really a bug, but I had to tweak two things in the plugin for my own use case:

*1. Set target framework version to 3.5, instead of 4.5*

My understanding is that Unity targets 3.5, so I don't understand why plugin sets it at 4.5?
I am using UniRx, which defines IObservable<T> and IObserver<T> because they did not exist in 3.5.  There are obviously mismatches when Unity compiles against 3.5 and Rider against 4.5.

*2. Set C# language version to 6.0*

I am using "Unity C# 5.0 and 6.0 Integration" (https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src), which does wonders, but Rider has to know the proper language version to use.

Maybe worth extracting possible values as constants and documenting how to tweak them, to ease people with different use cases.
 
Thanks again for your great contribution! :)

**Comment by van800** [comment]
Thank you for the feedback, I was plannig to add an options page.
Update to 4.5 is made to help with https://youtrack.jetbrains.com/issueMobile/RIDER-573
For Windows it is not necessary. Are you on Windows?

**Comment by van800** [comment]
I have pushed improvement for "1. Set target framework version to 3.5, instead of 4.5". It will not be done on windows.

**Comment by van800** [comment]
fixed by two commits:
https://github.com/JetBrains/Unity3dRider/commit/bc0fe7fe5bd3f6cea5c6be9439b292f5a646aa89
https://github.com/JetBrains/Unity3dRider/commit/95d6b9550cd01767c050c0e3267f540bae9c85c6

**Comment by van800** [comment]
https://github.com/JetBrains/Unity3dRider/commit/1600a7ac30d30a23dacf87749f72e0abfb4185b4
